const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const template=fs.readFileSync('templates/site.html','utf8');
const stamp=new Date().toISOString();
const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function entry(id,title,topics){const research=topics.includes('research')||topics.includes('hospital');return {sections:[research?'research':'industry'],categories:research?{research:['papers']}:{industry:['products']},stages:research?['validation']:[],id,t:title,te:title,s:'来源摘要',se:'summary',u:'https://example.org/'+id,src:'Test journal',sourceType:'期刊论文',topics,date:day,freshness:'fresh',tier:'skim',event:'new'};}
function page(change={}){
 const items=[entry('hospital','Hospital imaging AI',['hospital','research']),entry('ring','Wearable smart ring',['consumer'])];
 const payload={name:'健微知著',asOf:day,generatedAt:stamp,statusRaw:'complete',nSrc:12,items,top:items.map(i=>i.id),hot30:items,kws:[],srcs:[],briefing:'同一份简报',...change};
 const writes=[],errors=[];
 const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));
 const html=template.replace('__PAYLOAD__',JSON.stringify(payload).replaceAll('</','<\\/'));
 const dom=new JSDOM(html,{url:'https://example.org/ai-health-intel/',runScripts:'dangerously',virtualConsole:vc,beforeParse(window){window.scrollTo=()=>{};window.URL.createObjectURL=()=>"blob:test-screenshot";window.URL.revokeObjectURL=()=>{};Object.defineProperty(window.navigator,'clipboard',{value:{writeText:async text=>writes.push(text)}});}});
 return {dom,doc:dom.window.document,writes,errors};
}
test('initial render has full titles, same briefing, no JS errors',()=>{const p=page();assert.equal(p.errors.length,0);assert.equal(p.doc.querySelectorAll('#topRows article').length,1);assert.equal(p.doc.querySelector('#dailyText').textContent,'同一份简报');assert(!p.doc.body.textContent.includes('未经人工审核'));p.dom.window.close();});
test('keyword and topic filters operate together',()=>{const p=page();const w=p.dom.window;const topic=p.doc.querySelector('#topicFilter');topic.value='consumer';topic.dispatchEvent(new w.Event('change'));assert.equal(p.doc.querySelectorAll('#feedRows article').length,1);const search=p.doc.querySelector('#search');search.value='no match';search.dispatchEvent(new w.Event('input'));assert.equal(p.doc.querySelectorAll('#feedRows article').length,0);p.dom.window.close();});
test('mobile navigation opens cooperation and copies the authorized WeChat',async()=>{const p=page();const w=p.dom.window;w.location.hash='#about';w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert(p.doc.querySelector('#v-about').classList.contains('active'));p.doc.querySelector('#copyWechat').click();await Promise.resolve();assert.deepEqual(p.writes,['13028564458']);p.dom.window.close();});
test('source text is escaped and javascript links are rejected',()=>{const evil=entry('evil','<img src=x onerror=alert(1)>',['hospital']);evil.u='javascript:alert(1)';const p=page({items:[evil],top:['evil'],hot30:[evil]});assert.equal(p.doc.querySelectorAll('#topRows img').length,0);assert.equal(p.doc.querySelector('#topRows h3 a').getAttribute('href'),'#');assert.equal(p.errors.length,0);p.dom.window.close();});
test('a frozen old page expires recommendations and displays an update warning',()=>{const item=entry('old','Expired headline',['hospital']);item.date='2020-01-01';const p=page({generatedAt:'2020-01-01T00:00:00Z',asOf:'2020-01-01',items:[item],top:['old'],hot30:[item]});assert.equal(p.doc.querySelectorAll('#topRows article').length,0);assert.equal(p.doc.querySelector('#staleNotice').hidden,false);assert(!p.doc.querySelector('#dailyText').textContent.includes('Expired headline'));p.dom.window.close();});
test('unknown route recovers to home',()=>{const p=page();p.dom.window.location.hash='#unknown';p.dom.window.dispatchEvent(new p.dom.window.HashChangeEvent('hashchange'));assert(p.doc.querySelector('#v-jingxuan').classList.contains('active'));p.dom.window.close();});
test('clipboard refusal displays actionable fallback',async()=>{const p=page();p.dom.window.navigator.clipboard.writeText=async()=>{throw Error('denied');};p.doc.querySelector('#copyWechat').click();await new Promise(resolve=>setImmediate(resolve));assert.match(p.doc.querySelector('#toast').textContent,/长按/);p.dom.window.close();});

test('research is default and industry has its own feed',()=>{const p=page();assert(p.doc.querySelector('#v-jingxuan').classList.contains('active'));assert(p.doc.querySelector('#topRows').textContent.includes('Hospital imaging AI'));assert(!p.doc.querySelector('#topRows').textContent.includes('Wearable smart ring'));p.dom.window.location.hash='#industry';p.dom.window.dispatchEvent(new p.dom.window.HashChangeEvent('hashchange'));assert.equal(p.doc.querySelectorAll('#industryRows article').length,1);assert(p.doc.querySelector('#industryRows').textContent.includes('Wearable smart ring'));p.dom.window.close();});
test('section category search and stage combine without fallback filler',()=>{const p=page();const w=p.dom.window;w.location.hash='#jingxuan?category=policy';w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert.equal(p.doc.querySelectorAll('#topRows article').length,0);w.location.hash='#jingxuan?category=papers';w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert.equal(p.doc.querySelectorAll('#topRows article').length,1);p.doc.querySelector('#researchStage').value='data';p.doc.querySelector('#researchStage').dispatchEvent(new w.Event('change'));assert.equal(p.doc.querySelectorAll('#topRows article').length,0);p.doc.querySelector('#researchStage').value='all';p.doc.querySelector('#researchSearch').value='no match';p.doc.querySelector('#researchSearch').dispatchEvent(new w.Event('input'));assert.equal(p.doc.querySelectorAll('#topRows article').length,0);p.dom.window.close();});
test('timeline groups by source date and unknown category falls back',()=>{const p=page();const w=p.dom.window;w.location.hash='#jingxuan?category=bogus';w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert.equal(p.doc.querySelector('#topRows h2 time').textContent,day);assert.equal(p.doc.querySelectorAll('#topRows article').length,1);assert.equal(p.errors.length,0);p.dom.window.close();});

test('more menu links to access about and feedback without changelog',()=>{const p=page();const w=p.dom.window;w.location.hash='#more';w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert(p.doc.querySelector('#v-more').classList.contains('active'));assert.deepEqual([...p.doc.querySelectorAll('#v-more a')].map(x=>x.getAttribute('href')),['#connect','#about','#feedback']);assert(!p.doc.querySelector('.sidebar').textContent.includes('更新日志'));p.dom.window.close();});
test('access tabs and copy prompt use only SIH assets',async()=>{const p=page();const w=p.dom.window;for(const tab of ['skill','mcp','rss','api']){w.location.hash='#connect?tab='+tab;w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert.equal(p.doc.querySelector('#access-'+tab).hidden,false);assert.equal([...p.doc.querySelectorAll('.access-panel')].filter(x=>!x.hidden).length,1);}p.doc.querySelector('[data-copy-target="skillPrompt"]').click();await Promise.resolve();assert(p.writes[0].includes('/ai-health-intel/sih-intel.zip'));assert(!p.writes[0].includes('--actor'));w.location.hash='#connect?tab=bad';w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert.equal(p.doc.querySelector('#access-skill').hidden,false);p.dom.window.close();});
test('feedback checks empty length and email and never reports sent',async()=>{const p=page(),w=p.dom.window,t=p.doc.querySelector('#feedbackText'),email=p.doc.querySelector('#feedbackEmail'),b=p.doc.querySelector('#copyFeedback');assert(b.disabled);t.value='搜索结果有问题';t.dispatchEvent(new w.Event('input'));assert(!b.disabled);email.value='invalid';email.dispatchEvent(new w.Event('input'));assert(b.disabled);email.value='user@example.org';email.dispatchEvent(new w.Event('input'));assert(!b.disabled);p.doc.querySelector('#feedbackForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setImmediate(r));assert(p.writes[0].includes('搜索结果有问题'));assert(p.doc.querySelector('#feedbackStatus').textContent.includes('尚未发送'));t.value='x'.repeat(2001);t.dispatchEvent(new w.Event('input'));assert(b.disabled);assert.match(p.doc.querySelector('#feedbackCount').textContent,/2001/);p.dom.window.close();});
test('feedback screenshot validates type size and supports preview removal',()=>{const p=page(),w=p.dom.window,input=p.doc.querySelector('#feedbackImage');function select(file){Object.defineProperty(input,'files',{configurable:true,value:[file]});input.dispatchEvent(new w.Event('change'));}select(new w.File(['<svg/>'],'bad.svg',{type:'image/svg+xml'}));assert(p.doc.querySelector('#imagePreview').hidden);assert.match(p.doc.querySelector('#feedbackError').textContent,/5 MB/);select(new w.File([new Uint8Array(5*1024*1024+1)],'huge.png',{type:'image/png'}));assert(p.doc.querySelector('#imagePreview').hidden);select(new w.File(['fixture'],'test.png',{type:'image/png'}));assert(!p.doc.querySelector('#imagePreview').hidden);assert.equal(p.doc.querySelector('#imageName').textContent,'test.png');p.doc.querySelector('#removeImage').click();assert(p.doc.querySelector('#imagePreview').hidden);p.dom.window.close();});
test('about page uses June contact and no borrowed QR codes',()=>{const p=page();assert.match(p.doc.querySelector('#v-about h1').textContent,/孟思君 June/);assert.equal(p.doc.querySelector('#wechatNumber').textContent,'13028564458');assert.equal(p.doc.querySelectorAll('#v-about img').length,0);assert(p.doc.querySelector('#v-about a[href="https://1dc1742f.pinme.dev/"]'));p.dom.window.close();});
