const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const template=fs.readFileSync('templates/site.html','utf8');
const stamp=new Date().toISOString();
const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function entry(id,title,topics){const research=topics.includes('research')||topics.includes('hospital');return {sections:[research?'research':'industry'],categories:research?{research:['papers']}:{industry:['products']},stages:research?['validation']:[],id,t:title,te:title,s:'来源摘要',se:'summary',u:'https://example.org/'+id,src:'Test journal',sourceType:'期刊论文',topics,date:day,freshness:'fresh',tier:'skim',event:'new'};}
function page(change={},settings={}){
 const items=[entry('hospital','Hospital imaging AI',['hospital','research']),entry('ring','Wearable smart ring',['consumer'])];
 const payload={name:'奇点医研',asOf:day,generatedAt:stamp,statusRaw:'complete',nSrc:12,items,top:items.map(i=>i.id),hot30:items,kws:[],srcs:[],briefing:'同一份简报',dailyIssues:[{date:day,item_ids:items.map(i=>i.id),minutes:1}],...change};
 const writes=[],errors=[];
 const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));
 const html=template.replace('__PAYLOAD__',JSON.stringify(payload).replaceAll('</','<\\/'));
 const dom=new JSDOM(html,{url:'https://example.org/ai-health-intel/',runScripts:'dangerously',virtualConsole:vc,beforeParse(window){window.scrollTo=()=>{};window.themeMedia={matches:!!settings.dark,addEventListener:(name,fn)=>window.themeChange=fn};window.matchMedia=()=>window.themeMedia;if(settings.saved)window.localStorage.setItem('sih-theme',settings.saved);if(settings.storageBlocked)Object.defineProperty(window,'localStorage',{get(){throw Error('blocked');}});window.URL.createObjectURL=()=>"blob:test-screenshot";window.URL.revokeObjectURL=()=>{};Object.defineProperty(window.navigator,'clipboard',{value:{writeText:async text=>writes.push(text)}});}});
 return {dom,doc:dom.window.document,writes,errors};
}
test('initial render has full titles, same briefing, no JS errors',()=>{const p=page();assert.equal(p.errors.length,0);assert.equal(p.doc.querySelectorAll('#topRows article').length,1);assert.equal(p.doc.querySelectorAll('.digest-story').length,2);assert(p.doc.querySelector('#dailyTitle').textContent.includes('2 件'));assert(!p.doc.querySelector('#dailyText'));assert(!p.doc.body.textContent.includes('未经人工审核'));assert(!p.doc.querySelector('.topbar a'));assert(!p.doc.querySelector('.sidebar-foot').textContent.includes('June'));p.dom.window.close();});
test('keyword and topic filters operate together',()=>{const p=page();const w=p.dom.window;const topic=p.doc.querySelector('#topicFilter');topic.value='consumer';topic.dispatchEvent(new w.Event('change'));assert.equal(p.doc.querySelectorAll('#feedRows article').length,1);const search=p.doc.querySelector('#search');search.value='no match';search.dispatchEvent(new w.Event('input'));assert.equal(p.doc.querySelectorAll('#feedRows article').length,0);p.dom.window.close();});
test('mobile navigation opens cooperation and copies the authorized WeChat',async()=>{const p=page();const w=p.dom.window;w.location.hash='#about';w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert(p.doc.querySelector('#v-about').classList.contains('active'));p.doc.querySelector('#copyWechat').click();await Promise.resolve();assert.deepEqual(p.writes,['13028564458']);p.dom.window.close();});
test('source text is escaped and javascript links are rejected',()=>{const evil=entry('evil','<img src=x onerror=alert(1)>',['hospital']);evil.u='javascript:alert(1)';const p=page({items:[evil],top:['evil'],hot30:[evil]});assert.equal(p.doc.querySelectorAll('#topRows img').length,0);assert.equal(p.doc.querySelector('#topRows h3 a').getAttribute('href'),'#');assert.equal(p.errors.length,0);p.dom.window.close();});
test('a frozen old page expires recommendations and displays an update warning',()=>{const item=entry('old','Expired headline',['hospital']);item.date='2020-01-01';const p=page({generatedAt:'2020-01-01T00:00:00Z',asOf:'2020-01-01',items:[item],top:['old'],hot30:[item]});assert.equal(p.doc.querySelectorAll('#topRows article').length,0);assert.equal(p.doc.querySelector('#staleNotice').hidden,false);assert(!p.doc.querySelector('#dailyStories').textContent.includes('Expired headline'));p.dom.window.close();});
test('unknown route recovers to home',()=>{const p=page();p.dom.window.location.hash='#unknown';p.dom.window.dispatchEvent(new p.dom.window.HashChangeEvent('hashchange'));assert(p.doc.querySelector('#v-jingxuan').classList.contains('active'));p.dom.window.close();});
test('clipboard refusal displays actionable fallback',async()=>{const p=page();p.dom.window.navigator.clipboard.writeText=async()=>{throw Error('denied');};p.doc.querySelector('#copyWechat').click();await new Promise(resolve=>setImmediate(resolve));assert.match(p.doc.querySelector('#toast').textContent,/长按/);p.dom.window.close();});

test('research is default and industry has its own feed',()=>{const p=page();assert(p.doc.querySelector('#v-jingxuan').classList.contains('active'));assert(p.doc.querySelector('#topRows').textContent.includes('Hospital imaging AI'));assert(!p.doc.querySelector('#topRows').textContent.includes('Wearable smart ring'));p.dom.window.location.hash='#industry';p.dom.window.dispatchEvent(new p.dom.window.HashChangeEvent('hashchange'));assert.equal(p.doc.querySelectorAll('#industryRows article').length,1);assert(p.doc.querySelector('#industryRows').textContent.includes('Wearable smart ring'));p.dom.window.close();});
test('section category search and stage combine without fallback filler',()=>{const p=page();const w=p.dom.window;w.location.hash='#jingxuan?category=policy';w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert.equal(p.doc.querySelectorAll('#topRows article').length,0);w.location.hash='#jingxuan?category=papers';w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert.equal(p.doc.querySelectorAll('#topRows article').length,1);p.doc.querySelector('#researchStage').value='data';p.doc.querySelector('#researchStage').dispatchEvent(new w.Event('change'));assert.equal(p.doc.querySelectorAll('#topRows article').length,0);p.doc.querySelector('#researchStage').value='all';p.doc.querySelector('#researchSearch').value='no match';p.doc.querySelector('#researchSearch').dispatchEvent(new w.Event('input'));assert.equal(p.doc.querySelectorAll('#topRows article').length,0);p.dom.window.close();});
test('timeline groups by source date and unknown category falls back',()=>{const p=page();const w=p.dom.window;w.location.hash='#jingxuan?category=bogus';w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert.equal(p.doc.querySelector('#topRows h2 time').textContent,day);assert.equal(p.doc.querySelectorAll('#topRows article').length,1);assert.equal(p.errors.length,0);p.dom.window.close();});

test('more menu links to access about and feedback without changelog',()=>{const p=page();const w=p.dom.window;w.location.hash='#more';w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert(p.doc.querySelector('#v-more').classList.contains('active'));assert.deepEqual([...p.doc.querySelectorAll('#v-more a')].map(x=>x.getAttribute('href')),['#connect','#about','#feedback']);assert(!p.doc.querySelector('.sidebar').textContent.includes('更新日志'));p.dom.window.close();});
test('access tabs and copy prompt use only SIH assets',async()=>{const p=page();const w=p.dom.window;for(const tab of ['skill','mcp','rss','api']){w.location.hash='#connect?tab='+tab;w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert.equal(p.doc.querySelector('#access-'+tab).hidden,false);assert.equal([...p.doc.querySelectorAll('.access-panel')].filter(x=>!x.hidden).length,1);}p.doc.querySelector('[data-copy-target="skillPrompt"]').click();await Promise.resolve();assert(p.writes[0].includes('/ai-health-intel/sih-intel.zip'));assert(!p.writes[0].includes('--actor'));w.location.hash='#connect?tab=bad';w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert.equal(p.doc.querySelector('#access-skill').hidden,false);p.dom.window.close();});
test('feedback checks empty length and email and never reports sent',async()=>{const p=page(),w=p.dom.window,t=p.doc.querySelector('#feedbackText'),email=p.doc.querySelector('#feedbackEmail'),b=p.doc.querySelector('#copyFeedback');assert(b.disabled);t.value='搜索结果有问题';t.dispatchEvent(new w.Event('input'));assert(!b.disabled);email.value='invalid';email.dispatchEvent(new w.Event('input'));assert(b.disabled);email.value='user@example.org';email.dispatchEvent(new w.Event('input'));assert(!b.disabled);p.doc.querySelector('#feedbackForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setImmediate(r));assert(p.writes[0].includes('搜索结果有问题'));assert(p.doc.querySelector('#feedbackStatus').textContent.includes('尚未发送'));t.value='x'.repeat(2001);t.dispatchEvent(new w.Event('input'));assert(b.disabled);assert.match(p.doc.querySelector('#feedbackCount').textContent,/2001/);p.dom.window.close();});
test('feedback screenshot validates type size and supports preview removal',()=>{const p=page(),w=p.dom.window,input=p.doc.querySelector('#feedbackImage');function select(file){Object.defineProperty(input,'files',{configurable:true,value:[file]});input.dispatchEvent(new w.Event('change'));}select(new w.File(['<svg/>'],'bad.svg',{type:'image/svg+xml'}));assert(p.doc.querySelector('#imagePreview').hidden);assert.match(p.doc.querySelector('#feedbackError').textContent,/5 MB/);select(new w.File([new Uint8Array(5*1024*1024+1)],'huge.png',{type:'image/png'}));assert(p.doc.querySelector('#imagePreview').hidden);select(new w.File(['fixture'],'test.png',{type:'image/png'}));assert(!p.doc.querySelector('#imagePreview').hidden);assert.equal(p.doc.querySelector('#imageName').textContent,'test.png');p.doc.querySelector('#removeImage').click();assert(p.doc.querySelector('#imagePreview').hidden);p.dom.window.close();});
test('about page uses June contact and no borrowed QR codes',()=>{const p=page();assert.match(p.doc.querySelector('#v-about h1').textContent,/孟思君 June/);assert.equal(p.doc.querySelector('#wechatNumber').textContent,'13028564458');assert.equal(p.doc.querySelector('#v-about img').getAttribute('src'),'assets/community-qr.png');assert.equal(p.doc.querySelectorAll('.cooperation-grid article').length,3);assert(p.doc.querySelector('#v-about a[href="https://1dc1742f.pinme.dev/"]'));p.dom.window.close();});

test('themes persist explicit choice and follow live system changes',()=>{const p=page({}, {dark:true});const w=p.dom.window;assert.equal(p.doc.documentElement.dataset.theme,'dark');p.doc.querySelector('[data-theme-choice=light]').click();assert.equal(p.doc.documentElement.dataset.theme,'light');assert.equal(w.localStorage.getItem('sih-theme'),'light');w.themeChange();assert.equal(p.doc.documentElement.dataset.theme,'light');p.doc.querySelector('[data-theme-choice=system]').click();assert.equal(p.doc.documentElement.dataset.theme,'dark');w.themeMedia.matches=false;w.themeChange();assert.equal(p.doc.documentElement.dataset.theme,'light');assert.equal(p.doc.querySelectorAll('[data-theme-choice=system][aria-pressed=true]').length,2);p.dom.window.close();const saved=page({}, {saved:'dark'});assert.equal(saved.doc.documentElement.dataset.theme,'dark');saved.dom.window.close();});
test('blocked storage and invalid saved preference do not break theme or page',()=>{for(const settings of [{storageBlocked:true},{saved:'unknown'}]){const p=page({},settings);p.doc.querySelector('[data-theme-choice=dark]').click();assert.equal(p.doc.documentElement.dataset.theme,'dark');assert.equal(p.errors.length,0);p.dom.window.close();}});
test('daily date navigation and copy expose only selected dated stories',async()=>{const prior=new Date(Date.now()-86400000);const priorDay=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(prior);const a=entry('new','New study',['research']),b={...entry('previous','Previous study',['research']),date:priorDay};const p=page({items:[a,b],dailyIssues:[{date:day,item_ids:['new'],minutes:1},{date:priorDay,item_ids:['previous'],minutes:1}]});const w=p.dom.window;assert(p.doc.querySelector('#dailyStories').textContent.includes('New study'));w.location.hash='#daily?date='+priorDay;w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert(p.doc.querySelector('#dailyStories').textContent.includes('Previous study'));assert(!p.doc.querySelector('#dailyStories').textContent.includes('New study'));p.doc.querySelector('#copyBtn').click();await Promise.resolve();assert(p.writes[0].includes('Previous study'));assert(!p.writes[0].includes('New study'));assert(!/事实池|推荐产出|13028564458/.test(p.writes[0]));assert.equal(p.doc.querySelector('#dailyDateSelect').value,priorDay);w.location.hash='#daily?date=2020-01-01';w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert.equal(p.doc.querySelectorAll('.digest-story').length,0);assert.equal(p.doc.querySelector('#copyBtn').disabled,true);p.dom.window.close();});
test('daily story titles and summaries are escaped and unsafe links rejected',()=>{const evil={...entry('evil','<svg onload=alert(1)>',['research']),s:'<img src=x>',u:'javascript:alert(1)'};const p=page({items:[evil],dailyIssues:[{date:day,item_ids:['evil'],minutes:1}]});assert.equal(p.doc.querySelectorAll('#dailyStories svg,#dailyStories img').length,0);assert.equal(p.doc.querySelector('#dailyStories h2 a').getAttribute('href'),'#');assert.equal(p.errors.length,0);p.dom.window.close();});

test('selection pages put categories and content before operational details',()=>{const p=page();for(const id of ['v-jingxuan','v-industry']){const view=p.doc.getElementById(id);assert(!view.querySelector('.eyebrow,.sub,.metrics,.update-line'));assert(!view.textContent.includes('最近采集'));assert.equal(view.querySelector('h1').textContent,id==='v-jingxuan'?'医学科研':'产业前沿');assert(view.querySelector('.selection-toolbar .category-tabs'));assert(view.querySelector('.selection-toolbar input[type=search]'));assert.equal(view.querySelector('.highlights h2').textContent,'重点速览');}assert.equal(p.doc.querySelector('.brand-name').textContent,'奇点医研');assert.equal(p.doc.querySelector('.brand small').textContent,'SINGULARITY MED');assert.equal(p.errors.length,0);p.dom.window.close();});

test('removed source page falls back safely while Agent health API remains',()=>{const p=page(),w=p.dom.window;assert(!p.doc.querySelector('#v-health'));assert(!p.doc.querySelector('a[href="#health"]'));w.location.hash='#health';w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert(p.doc.querySelector('#v-jingxuan').classList.contains('active'));assert(p.doc.querySelector('#apiUrls').textContent.includes('health.json'));assert(p.doc.querySelector('.publisher').textContent.includes('循证奇点出品'));assert.equal(p.doc.querySelectorAll('.brand-mark').length,2);assert.equal(p.errors.length,0);p.dom.window.close();});


test('audience reasons are escaped and industry labels have four characters',()=>{const a=entry('both','Shared article',['research']);a.sections=['research','industry'];a.categories={research:['papers'],industry:['products']};a.reasons={research:'临床课题 <img src=x>',industry:'产品升级'};const p=page({items:[a],hot30:[a]});assert.match(p.doc.querySelector('#topRows .recommendation').textContent,/临床课题/);assert.equal(p.doc.querySelectorAll('#topRows img').length,0);p.dom.window.location.hash='#industry';p.dom.window.dispatchEvent(new p.dom.window.HashChangeEvent('hashchange'));assert.match(p.doc.querySelector('#industryRows .recommendation').textContent,/产品升级/);assert([...p.doc.querySelectorAll('#industryTabs a')].slice(1).every(a=>a.textContent.length===4));p.dom.window.close();});

test('history is opt in and never fills current highlights or RSS views',()=>{const old={...entry('history','Historical study',['research']),date:new Date(Date.now()-15*86400000).toISOString().slice(0,10),historical:true};const p=page({historyItems:[old],historyIssues:[{date:old.date,item_ids:[old.id],minutes:1}]});assert(!p.doc.querySelector('#topRows').textContent.includes(old.t));const select=p.doc.querySelector('#researchWindow');select.value='history';select.dispatchEvent(new p.dom.window.Event('change'));assert(p.doc.querySelector('#topRows').textContent.includes(old.t));assert(!p.doc.querySelector('#researchHighlights').textContent.includes(old.t));assert(!p.doc.querySelector('#feedRows').textContent.includes(old.t));p.dom.window.location.hash='#daily?date='+old.date;p.dom.window.dispatchEvent(new p.dom.window.HashChangeEvent('hashchange'));assert(p.doc.querySelector('#dailyStories').textContent.includes(old.t));assert.equal(p.errors.length,0);p.dom.window.close();});

test('policy journey filters pilots and escapes source text',()=>{const base={date:'2026-08-25',country:'中国',kind:'政策',title:'AI 文件 <img>',source:'官方',url:'javascript:bad()',change:'变化',meaning:'解读',boundary:'边界',date_note:'署期8月18日',stage:'应用'};const p=page({policyTimeline:{items:[{...base,pilot:false},{...base,pilot:true,title:'试点'}]}});assert.equal(p.doc.querySelectorAll('#policyRows .policy-node').length,2);assert.equal(p.doc.querySelectorAll('#policyRows img').length,0);assert.equal(p.doc.querySelector('#policyRows a').getAttribute('href'),'#');const select=p.doc.querySelector('#policyRegion');select.value='pilot';select.dispatchEvent(new p.dom.window.Event('change'));assert.equal(p.doc.querySelectorAll('#policyRows .policy-node').length,1);assert.match(p.doc.querySelector('#policyRows').textContent,/试点/);p.dom.window.close();});


test('policy map separates countries, orders each lane and links nodes to originals',()=>{const row=(country,date,title)=>({country,date,title,kind:'政策',url:'https://example.org/'+title,source:'官方',change:'变化',meaning:'意义',boundary:'边界'});const p=page({policyTimeline:{items:[row('中国','2026-08-25','cn-new'),row('美国','2025-01','us'),row('中国','2021-08-20','cn-old')]}});assert.equal(p.doc.querySelectorAll('.policy-lane').length,2);assert.deepEqual([...p.doc.querySelectorAll('[data-country="中国"] .policy-node h3')].map(e=>e.textContent),['cn-old','cn-new']);const node=p.doc.querySelector('[data-country="美国"] .policy-node');assert.equal(node.getAttribute('href'),'https://example.org/us');assert.equal(node.target,'_blank');assert.equal(p.doc.querySelector('.policy-scroll').tabIndex,0);assert(!p.doc.querySelector('.policy-years,.journey-path'));const select=p.doc.querySelector('#policyRegion');select.value='美国';select.dispatchEvent(new p.dom.window.Event('change'));assert.equal(p.doc.querySelectorAll('.policy-lane').length,1);assert.equal(p.doc.querySelector('.policy-lane').dataset.country,'美国');assert.equal(p.errors.length,0);p.dom.window.close();});

test('renamed methods tab works and removed industry category falls back to all',()=>{const p=page(),w=p.dom.window;assert.equal(p.doc.querySelector('#researchTabs a[href="#jingxuan?category=methods"]').textContent,'工具方法');w.location.hash='#industry?category=overview';w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert(!p.doc.querySelector('#industryTabs a[href="#industry?category=overview"]'));assert(!p.doc.querySelector('#industryTabs').textContent.includes('综合动态'));assert.equal(p.doc.querySelector('#industryTabs [aria-current="page"]').textContent,'全部');p.dom.window.close();});


test('policy tab directly displays both maps, restores articles and supports old map URL',()=>{const items=['中国','美国'].map((country,n)=>({country,date:'2026-01',title:'政策'+n,url:'https://example.org/policy'+n,source:'官方',kind:'指南',change:'变化',meaning:'意义',boundary:'边界'}));const p=page({policyTimeline:{items}}),w=p.dom.window;const visit=hash=>{w.location.hash=hash;w.dispatchEvent(new w.HashChangeEvent('hashchange'));};visit('#jingxuan?category=policy');assert(p.doc.querySelector('#v-jingxuan').classList.contains('active'));assert.equal(p.doc.querySelector('#policyMap').hidden,false);assert.equal(p.doc.querySelectorAll('#policyMap .policy-lane').length,2);assert.equal(p.doc.querySelector('#researchTabs [aria-current="page"]').textContent,'政策动态');assert(p.doc.querySelector('#topRows').hidden);assert(p.doc.querySelector('#researchSearch').closest('.section-filters').hidden);assert(p.doc.querySelector('#researchWindow').closest('.archive-toolbar').hidden);assert(!p.doc.querySelector('#policyLibrary,#v-policy'));assert(!p.doc.querySelector('#v-jingxuan a[href="#policy"]'));visit('#jingxuan?category=papers');assert(p.doc.querySelector('#policyMap').hidden);assert(!p.doc.querySelector('#topRows').hidden);assert(!p.doc.querySelector('#researchSearch').closest('.section-filters').hidden);assert(!p.doc.querySelector('#researchWindow').closest('.archive-toolbar').hidden);visit('#policy');assert(!p.doc.querySelector('#policyMap').hidden);assert(p.doc.querySelector('#v-jingxuan').classList.contains('active'));assert.equal(p.errors.length,0);p.dom.window.close();});
